const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
  stories: ['../doc/**/*.mdx', '../doc/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials', '@storybook/addon-interactions'],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    docsPage: true,
  },
  webpackFinal: async (config /* , { configType } */) => {
    const cssRule = config.module.rules.find((rule) => rule?.test?.test?.('test.css'))
    cssRule.test = /.*(?<!\.vanilla)\.css$/

    // Append vanilla-extract loader to extract CSS from components
    config.module.rules.push({
      test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
      use: [
        MiniCssExtractPlugin.loader,
        {
          loader: require.resolve('css-loader'),
          options: {
            url: false, // Required as image imports should be handled via JS/TS import statements
          },
        },
      ],
    })

    config.plugins.push(new VanillaExtractPlugin(), new MiniCssExtractPlugin())

    // Return the altered config
    return config
  },
}
